import 'package:intl/intl.dart';
import 'package:swasthyasetu_ai/domain/models/environment.dart';
import 'package:swasthyasetu_ai/domain/models/patient.dart';
import 'package:swasthyasetu_ai/domain/models/user_account.dart';
import 'package:swasthyasetu_ai/domain/rules/trend_engine.dart';

/// Builds the plain-text health summary a patient hands to a doctor.
///
/// Text, not PDF: it pastes into WhatsApp and SMS as-is, reads fine printed
/// by any clinic, and costs no new dependency or native print plumbing. The
/// sharing is user-initiated through the OS share sheet — the app never
/// transmits anywhere itself.
///
/// Structure is fixed and labelled so a scanning doctor finds the numbers in
/// 5 seconds; everything absent is omitted rather than rendered "N/A".
class HealthReport {
  HealthReport._();

  static String build({
    required UserAccount account,
    required Patient patient,
    required Screening latest,
    List<BaselineNote> trendNotes = const [],
    EnvironmentReading? environment,
  }) {
    final b = StringBuffer();
    final dateFormat = DateFormat('d MMM yyyy, h:mm a');

    b.writeln('SwasthyaSetu AI — Health Summary');
    b.writeln('Shared by the patient · ${
        dateFormat.format(DateTime.now())}');

    b.writeln();
    b.writeln('PATIENT');
    b.writeln('Name: ${patient.name}');
    if (account.age != null) b.writeln('Age: ${account.age}');
    if (account.sex.isNotEmpty) {
      b.writeln('Sex: ${switch (account.sex) {
        'F' => 'Female',
        'M' => 'Male',
        _ => 'Other',
      }}');
    }
    if (account.heightCm != null && account.weightKg != null) {
      final bmi = account.bmi;
      b.writeln(
          'Build: ${account.heightCm!.toStringAsFixed(0)} cm, ${account.weightKg!.toStringAsFixed(1)} kg'
          '${bmi != null ? ' (BMI ${bmi.toStringAsFixed(1)})' : ''}');
    }
    if (account.conditions.isNotEmpty) {
      b.writeln('Pre-existing conditions: ${account.conditions.join(', ')}');
    }
    final complaint = account.problems;
    if (complaint != null && complaint.trim().isNotEmpty) {
      b.writeln('Currently reported problems: $complaint');
    }

    b.writeln();
    b.writeln('LATEST SCREENING — ${dateFormat.format(latest.timestamp)}');
    b.writeln('Triage band: ${latest.riskLevel} (score ${latest.riskScore})');
    if (latest.recommendedAction.isNotEmpty) {
      b.writeln('Engine guidance: ${latest.recommendedAction}');
    }
    if (latest.heartRate > 0) {
      b.writeln('Heart rate: ${latest.heartRate} bpm');
    }
    if (latest.spo2 > 0) b.writeln('SpO₂: ${latest.spo2}%');
    b.writeln('Temperature: ${latest.temperature.toStringAsFixed(1)} °C');
    if (latest.isEcgTrustworthy) {
      b.writeln('ECG rhythm summary: ${latest.ecgRhythm}');
    }
    if (latest.hasBpEstimate) {
      b.writeln('Cuffless BP estimate (EXPERIMENTAL, not validated): '
          '${latest.estimatedSystolic}/${latest.estimatedDiastolic} mmHg');
    }
    if (latest.symptoms.isNotEmpty) {
      b.writeln('Symptoms: ${latest.symptoms.join(', ')}');
    }

    if (trendNotes.isNotEmpty) {
      b.writeln();
      b.writeln('TREND vs OWN BASELINE (last 30 days)');
      for (final n in trendNotes) {
        final direction = n.delta > 0 ? 'above' : 'below';
        if (n.metricId == 'hr') {
          b.writeln('• Pulse ${n.delta.abs().round()} bpm $direction usual');
        } else if (n.metricId == 'spo2') {
          b.writeln(
              '• SpO₂ ${n.delta.abs().toStringAsFixed(0)} pts $direction usual');
        } else if (n.metricId == 'temp') {
          b.writeln(
              '• Temperature ${n.delta.abs().toStringAsFixed(1)}°C $direction usual');
        }
      }
    }

    if (environment != null) {
      b.writeln();
      b.writeln('ENVIRONMENT NOW (for context)');
      b.writeln(
          'Feels like ${environment.apparentTemperatureC.round()}°C, '
          'humidity ${environment.humidityPercent.round()}%'
          '${environment.aqiUs != null ? ', AQI ${environment.aqiUs}' : ''}');
    }

    b.writeln();
    b.writeln('—');
    b.writeln('Generated by a screening/decision-support prototype. Not a '
        'medical diagnosis. Sensor data is not clinically verified. Please '
        'evaluate the patient clinically.');

    return b.toString().trim();
  }
}
